name: Generate Jars
on: [ push, pull_request ]
jobs:
  paperclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v4
        with:
          name: shreddedpaper.jar
          path: build/libs/shreddedpaper-paperclip-*-mojmap.jar
